// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DanielTitkov/weavle/ent/story"
	"github.com/google/uuid"
)

// Story is the model entity for the Story schema.
type Story struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status story.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StoryQuery when eager-loading is set.
	Edges        StoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StoryEdges holds the relations/edges for other nodes in the graph.
type StoryEdges struct {
	// Sentences holds the value of the sentences edge.
	Sentences []*Sentence `json:"sentences,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SentencesOrErr returns the Sentences value or an error if the edge
// was not loaded in eager-loading.
func (e StoryEdges) SentencesOrErr() ([]*Sentence, error) {
	if e.loadedTypes[0] {
		return e.Sentences, nil
	}
	return nil, &NotLoadedError{edge: "sentences"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Story) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case story.FieldStatus:
			values[i] = new(sql.NullString)
		case story.FieldCreatedAt, story.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case story.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Story fields.
func (s *Story) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case story.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				s.ID = *value
			}
		case story.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				s.Status = story.Status(value.String)
			}
		case story.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case story.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Story.
// This includes values selected through modifiers, order, etc.
func (s *Story) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QuerySentences queries the "sentences" edge of the Story entity.
func (s *Story) QuerySentences() *SentenceQuery {
	return NewStoryClient(s.config).QuerySentences(s)
}

// Update returns a builder for updating this Story.
// Note that you need to call Story.Unwrap() before calling this method if this Story
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Story) Update() *StoryUpdateOne {
	return NewStoryClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Story entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Story) Unwrap() *Story {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Story is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Story) String() string {
	var builder strings.Builder
	builder.WriteString("Story(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", s.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Stories is a parsable slice of Story.
type Stories []*Story
